name: Execute all the tasks
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Execute all the tasks
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.TOKEN }}
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          # Replace this with your goodreads user id
          goodreads_user_id: "5312887"
          shelf: "developer"
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: fundor333
          gif_out_path: dist/github-snake.gif
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name github-actions[bot]
          git config user.email github@fundor333.com
          git add .
          git commit -m "Update README"
          git push
          fi

